/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppLinhaDoTempoRouteImport } from './routes/_authenticated.app.linha-do-tempo'
import { Route as AuthenticatedAppIaClinicaRouteImport } from './routes/_authenticated.app.ia-clinica'
import { Route as AuthenticatedAppGenossociogramasRouteImport } from './routes/_authenticated.app.genossociogramas'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated.app.configuracoes'
import { Route as AuthenticatedAppBibliotecaRouteImport } from './routes/_authenticated.app.biblioteca'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated.app.agenda'
import { Route as AuthenticatedAppClientesIndexRouteImport } from './routes/_authenticated.app.clientes.index'
import { Route as AuthenticatedAppPacienteIdRouteImport } from './routes/_authenticated.app.paciente.$id'
import { Route as AuthenticatedAppClientesClientIdRouteImport } from './routes/_authenticated.app.clientes.$clientId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppLinhaDoTempoRoute =
  AuthenticatedAppLinhaDoTempoRouteImport.update({
    id: '/app/linha-do-tempo',
    path: '/app/linha-do-tempo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppIaClinicaRoute =
  AuthenticatedAppIaClinicaRouteImport.update({
    id: '/app/ia-clinica',
    path: '/app/ia-clinica',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppGenossociogramasRoute =
  AuthenticatedAppGenossociogramasRouteImport.update({
    id: '/app/genossociogramas',
    path: '/app/genossociogramas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/app/configuracoes',
    path: '/app/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppBibliotecaRoute =
  AuthenticatedAppBibliotecaRouteImport.update({
    id: '/app/biblioteca',
    path: '/app/biblioteca',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/app/agenda',
  path: '/app/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppClientesIndexRoute =
  AuthenticatedAppClientesIndexRouteImport.update({
    id: '/app/clientes/',
    path: '/app/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPacienteIdRoute =
  AuthenticatedAppPacienteIdRouteImport.update({
    id: '/app/paciente/$id',
    path: '/app/paciente/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppClientesClientIdRoute =
  AuthenticatedAppClientesClientIdRouteImport.update({
    id: '/app/clientes/$clientId',
    path: '/app/clientes/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/genossociogramas': typeof AuthenticatedAppGenossociogramasRoute
  '/app/ia-clinica': typeof AuthenticatedAppIaClinicaRoute
  '/app/linha-do-tempo': typeof AuthenticatedAppLinhaDoTempoRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/clientes/$clientId': typeof AuthenticatedAppClientesClientIdRoute
  '/app/paciente/$id': typeof AuthenticatedAppPacienteIdRoute
  '/app/clientes/': typeof AuthenticatedAppClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/genossociogramas': typeof AuthenticatedAppGenossociogramasRoute
  '/app/ia-clinica': typeof AuthenticatedAppIaClinicaRoute
  '/app/linha-do-tempo': typeof AuthenticatedAppLinhaDoTempoRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/clientes/$clientId': typeof AuthenticatedAppClientesClientIdRoute
  '/app/paciente/$id': typeof AuthenticatedAppPacienteIdRoute
  '/app/clientes': typeof AuthenticatedAppClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/genossociogramas': typeof AuthenticatedAppGenossociogramasRoute
  '/_authenticated/app/ia-clinica': typeof AuthenticatedAppIaClinicaRoute
  '/_authenticated/app/linha-do-tempo': typeof AuthenticatedAppLinhaDoTempoRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/clientes/$clientId': typeof AuthenticatedAppClientesClientIdRoute
  '/_authenticated/app/paciente/$id': typeof AuthenticatedAppPacienteIdRoute
  '/_authenticated/app/clientes/': typeof AuthenticatedAppClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/agenda'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/genossociogramas'
    | '/app/ia-clinica'
    | '/app/linha-do-tempo'
    | '/app/'
    | '/app/clientes/$clientId'
    | '/app/paciente/$id'
    | '/app/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/agenda'
    | '/app/biblioteca'
    | '/app/configuracoes'
    | '/app/genossociogramas'
    | '/app/ia-clinica'
    | '/app/linha-do-tempo'
    | '/app'
    | '/app/clientes/$clientId'
    | '/app/paciente/$id'
    | '/app/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/biblioteca'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/genossociogramas'
    | '/_authenticated/app/ia-clinica'
    | '/_authenticated/app/linha-do-tempo'
    | '/_authenticated/app/'
    | '/_authenticated/app/clientes/$clientId'
    | '/_authenticated/app/paciente/$id'
    | '/_authenticated/app/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/linha-do-tempo': {
      id: '/_authenticated/app/linha-do-tempo'
      path: '/app/linha-do-tempo'
      fullPath: '/app/linha-do-tempo'
      preLoaderRoute: typeof AuthenticatedAppLinhaDoTempoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/ia-clinica': {
      id: '/_authenticated/app/ia-clinica'
      path: '/app/ia-clinica'
      fullPath: '/app/ia-clinica'
      preLoaderRoute: typeof AuthenticatedAppIaClinicaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/genossociogramas': {
      id: '/_authenticated/app/genossociogramas'
      path: '/app/genossociogramas'
      fullPath: '/app/genossociogramas'
      preLoaderRoute: typeof AuthenticatedAppGenossociogramasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/app/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/biblioteca': {
      id: '/_authenticated/app/biblioteca'
      path: '/app/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AuthenticatedAppBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/app/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/clientes/': {
      id: '/_authenticated/app/clientes/'
      path: '/app/clientes'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AuthenticatedAppClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/paciente/$id': {
      id: '/_authenticated/app/paciente/$id'
      path: '/app/paciente/$id'
      fullPath: '/app/paciente/$id'
      preLoaderRoute: typeof AuthenticatedAppPacienteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/clientes/$clientId': {
      id: '/_authenticated/app/clientes/$clientId'
      path: '/app/clientes/$clientId'
      fullPath: '/app/clientes/$clientId'
      preLoaderRoute: typeof AuthenticatedAppClientesClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppBibliotecaRoute: typeof AuthenticatedAppBibliotecaRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppGenossociogramasRoute: typeof AuthenticatedAppGenossociogramasRoute
  AuthenticatedAppIaClinicaRoute: typeof AuthenticatedAppIaClinicaRoute
  AuthenticatedAppLinhaDoTempoRoute: typeof AuthenticatedAppLinhaDoTempoRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppClientesClientIdRoute: typeof AuthenticatedAppClientesClientIdRoute
  AuthenticatedAppPacienteIdRoute: typeof AuthenticatedAppPacienteIdRoute
  AuthenticatedAppClientesIndexRoute: typeof AuthenticatedAppClientesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppBibliotecaRoute: AuthenticatedAppBibliotecaRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppGenossociogramasRoute: AuthenticatedAppGenossociogramasRoute,
  AuthenticatedAppIaClinicaRoute: AuthenticatedAppIaClinicaRoute,
  AuthenticatedAppLinhaDoTempoRoute: AuthenticatedAppLinhaDoTempoRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppClientesClientIdRoute: AuthenticatedAppClientesClientIdRoute,
  AuthenticatedAppPacienteIdRoute: AuthenticatedAppPacienteIdRoute,
  AuthenticatedAppClientesIndexRoute: AuthenticatedAppClientesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
